# number: '0123456789'
# symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
# lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
number: '०१२३४५६७८९'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~।॥—₹₨‘’“”…"
lang_char: 'अआइईउऊऋएऐओऔअंअःकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसहक्षत्रज्ञािीुूृेैोौंःँॅॉ'
# number: '०१२३४५६७८९0123456789'
# symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~।॥—₹₨‘’“”…"
# lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzअआइईउऊऋएऐओऔअंअःकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसहक्षत्रज्ञािीुूृेैोौंःँॅॉ'
experiment_name: 'ne'
train_data: 'all_data'
valid_data: 'all_data/dataset/val'
manualSeed: 1111
workers: 8
batch_size: 32 #32
num_iter: 20000
valInterval: 200
saved_model: '' #'saved_models/en_filtered/iter_300000.pth'
FT: False
optim: adam # default is Adadelta
lr: 0.0005
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'dataset' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 100
imgH: 64
imgW: 1156
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
Prediction: 'Attn'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False